### ISSUE TITLE
pretrained models or datasets

### ISSUE THREAD

**Issue by sysau** [andreaspastor/Dynamic-HandGesture-Detection#1]
hi, interesting work!
which dataset  used for training? 
could you please open the pretrained models?

**Comment by shakram02** [comment]
@sysau  check [this](https://github.com/andreaspastor/HandGesture-Detection) out

**Comment by developer888891** [comment]
Hi.. thanks for the repo! I tried training the model with JESTER Dataset which I downloaded from https://20bn.com/datasets/jester/v1#download after that I extracted the dataset in project folder. Later run the code dataDump.py, it created a folder 'dataTrain' with Xtest, Xtrain, Ytest, Ytrain npy files in it. Then I run trainModel.py, its giving below error 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file final_model-10/best_model: Failed precondition: final_model-10/best_model; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_29 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_29/tensor_names, save/RestoreV2_29/shape_and_slices)]]
	 [[Node: save/RestoreV2_23/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_144_save/RestoreV2_23", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


Its not able to find 'best_model' file. Please help me in solving this issue.

Thank You!

**Comment by developer888891** [comment]
Hi.. thanks for the repo! I tried training the model with JESTER Dataset which I downloaded from https://20bn.com/datasets/jester/v1#download after that I extracted the dataset in project folder. Later run the code dataDump.py, it created a folder 'dataTrain' with Xtest, Xtrain, Ytest, Ytrain npy files in it. Then I run trainModel.py, its giving below error.

WARNING:tensorflow:From trainModel.py:193: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Tensor("conv1a_dropout/mul:0", shape=(?, 64, 64, 64), dtype=float32)
Tensor("Reshape:0", shape=(?, 8192), dtype=float32)
Tensor("add_9:0", shape=(?, 27), dtype=float32)
WARNING:tensorflow:From trainModel.py:204: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

2018-12-21 11:26:00.452690: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-21 11:26:00.543713: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-21 11:26:00.543952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.24GiB
2018-12-21 11:26:00.543965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-12-21 11:26:05.079575: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.079748: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.079848: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.079996: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080011: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080058: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080246: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080266: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080372: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080506: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080602: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080755: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080839: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.080996: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081020: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081128: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081202: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081247: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081053: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081343: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081409: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081449: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081528: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081574: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081694: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081708: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081841: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.081920: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082049: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082081: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082123: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082191: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082280: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082304: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082362: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082448: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082501: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082552: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082646: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082674: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082704: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082772: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082835: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082913: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082964: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.082981: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083102: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083168: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083225: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083263: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083340: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083390: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083433: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083508: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083565: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083619: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083692: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083771: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083905: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.083953: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.084025: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
2018-12-21 11:26:05.084122: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
	 [[Node: save/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_4/tensor_names, save/RestoreV2_4/shape_and_slices)]]
	 [[Node: save/RestoreV2_54/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_150_save/RestoreV2_54", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trainModel.py", line 225, in <module>
    saver.restore(sess=sess, save_path=save_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
	 [[Node: save/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_4/tensor_names, save/RestoreV2_4/shape_and_slices)]]
	 [[Node: save/RestoreV2_54/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_150_save/RestoreV2_54", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2_4', defined at:
  File "trainModel.py", line 212, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 765, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 268, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1031, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for final_model-10/best_model
	 [[Node: save/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_4/tensor_names, save/RestoreV2_4/shape_and_slices)]]
	 [[Node: save/RestoreV2_54/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_150_save/RestoreV2_54", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]




Its not able to find 'best_model' file. Please help me in solving this issue.
Thank You!

**Comment by Lihongjian520** [comment]
I have a problem, 
Here are my questions
 
recuperation done
Tensor("conv1a_dropout/mul:0", shape=(?, 64, 64, 32), dtype=float32)
Tensor("Reshape:0", shape=(?, 2048), dtype=float32)
Tensor("add_6:0", shape=(?, 5), dtype=float32)

Traceback (most recent call last):
  File "H:\4gestures\trainModel.py", line 211, in <module>
    res[no] = accuracy.eval({x:X_testClass[no][:batch_size], y:y_testClass[no][:batch_size], keep_prob: 1})
TypeError: 'int' object is not subscriptable
Can it be solved???
